# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tHFBAJiC6IfntzpDwDAMoNT_yNij6X8O
"""

import pandas as pd
data = pd.read_csv('housing.csv')

class DatasetView:
  def viewtop(self ,data):
    self.data = data
    view = self.data.head()
    return view