# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tHFBAJiC6IfntzpDwDAMoNT_yNij6X8O
"""

import pandas as pd
data = pd.read_csv('housing.csv')

class test:
  def testf(self, data):
    self.data = data
    top = self.data.head()
    bottom = self.data.tail()
    value = self.data.values()